name: CI Workflow

on:
  push:
    branches:
      - develop
      - feature/develop/task5
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r TicTacToeSWPart/requirements.txt
          pip install pytest

      # Install Arduino CLI on Windows
      - name: Set up Arduino CLI
        run: |
          Invoke-WebRequest -Uri https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Windows_64bit.zip -OutFile arduino-cli.zip
          Expand-Archive -Path arduino-cli.zip -DestinationPath C:\arduino-cli
          $env:PATH += ";C:\arduino-cli"
          arduino-cli config init

      # Install Arduino AVR core
      - name: Install Arduino AVR core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr  # Install the Arduino AVR core

      # Install ArduinoJson library
      - name: Install ArduinoJson library
        run: |
          arduino-cli lib install ArduinoJson

      # Compile Arduino Sketch for Arduino Nano (Old Bootloader)
      - name: Compile Arduino Sketch
        run: |
          mkdir build
          arduino-cli compile --fqbn arduino:avr:nano:cpu=atmega328old --output-dir build HWPart/TicTacToe/TicTacToe.ino

      # Run tests using the PowerShell script
      - name: Run Tests
        run: |
          PowerShell -ExecutionPolicy Bypass -File ./CI/RunTestsWindows.ps1

      # Upload compiled binaries as artifacts
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: compiled-files
          path: build/*.bin

      # Collect test results as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/*.xml
